version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always

  authdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "ThisIsMyAuthVeryStrong@Password"
      ACCEPT_EULA: "Y"
    ports:
      - "5064:1433"

  authservice:
    build:
      context: ./AuthService
    ports:
      - "8001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - authdb
      - rabbitmq

  alertdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "ThisIsMyAlertVeryStrong@Password"
      ACCEPT_EULA: "Y"
    ports:
      - "5067:1433"

  alertservice:
    build:
      context: ./AlertService
    ports:
      - "8002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - alertdb
      - rabbitmq

  diagnosisdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "ThisIsMyDiagnosisVeryStrong@Password"
      ACCEPT_EULA: "Y"
    ports:
      - "5069:1433"

  diagnosisservice:
    build:
      context: ./DiagnosisService
    ports:
      - "8003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - diagnosisdb
      - rabbitmq

  homerecoverydb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "ThisIsMyHomeRecoveryVeryStrong@Password"
      ACCEPT_EULA: "Y"
    ports:
      - "5070:1433"

  homerecoveryservice:
    build:
      context: ./HomeRecoveryService
    ports:
      - "8004:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - homerecoverydb
      - rabbitmq

  monitoringdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "ThisIsMyMonitoringVeryStrong@Password"
      ACCEPT_EULA: "Y"
    ports:
      - "5066:1433"

  monitoringservice:
    build:
      context: ./MonitoringService
    ports:
      - "8005:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - monitoringdb
      - rabbitmq

  patientdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "ThisIsMyPatientVeryStrong@Password"
      ACCEPT_EULA: "Y"
    ports:
      - "5065:1433"

  patientservice:
    build:
      context: ./PatientService
    ports:
      - "8006:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - patientdb
      - rabbitmq

  rehabilitationdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "ThisIsMyRehabVeryStrong@Password"
      ACCEPT_EULA: "Y"
    ports:
      - "5068:1433"

  rehabilitationservice:
    build:
      context: ./RehabilitationService
    ports:
      - "8007:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rehabilitationdb
      - rabbitmq

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - authservice
      - alertservice
      - diagnosisservice
      - homerecoveryservice
      - monitoringservice
      - patientservice
      - rehabilitationservice
